version: "2.22"
services:
  centos:
    image: centos:ssh
    privileged: true
    container_name: centos_ssh
    ports:
      - 2222:22
    volumes:
      - type: bind
        source: ~/.ssh/id_rsa_shared.pub
        target: /home/${USR}/.ssh/authorized_keys
        read_only: true